title: Krishna Gudipaty
url: "https://ankitsultana.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/krishna-praneet/krishna-praneet.github.io/tree/gh-pages"
footer_text: "Website ideation by: Krishna Gudipaty, and modifications by: Claude (click for source)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Academia"
   link: "academia"
 - name: "Contact"
   link: "contact"
